recipe: default.v1

language: en

assistant_id: ornery-ion

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
    active: false
  fallback_threshold: 0.70
  pattern_threshold: 0.90

policies:
- name: FlowPolicy
